export const SET_TEXT = 'SET_TEXT';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_WEATHER_DETAILS = 'SET_WEATHER_DETAILS';
export const SET_WEEKLY_DATA = 'SET_WEEKLY_DATA';
export const SET_SHOW_CELSIUS = 'SET_SHOW_CELSIUS';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';

